Indentation fix
mipt-diht/mipt-latex-fall2018-enscogitans pull request #2
Opened 2018-10-25 16:12 UTC by enscogitans

2018-10-25 16:31 UTC, AShepelevv commented
И что ты поправил?

2018-10-25 16:33 UTC, enscogitans commented
"@enscogitans Нужно отступы поправить, закоммитить в task1 и сделать новый PR."

2018-10-29 13:58 UTC, AShepelevv commented
@enscogitans Но ведь ничего не изменилось, перед "Заголовка" попрежнему  28pt + абзацный отступ. А второго слагаемого быть не должно.

2018-10-29 13:59 UTC, AShepelevv requested changes

2018-10-29 13:59 UTC, AShepelevv commented on task1.tex
>  	\hspace{28pt}{\Large\textbf{Геометрия \hfill Планиметрия}}
Слишком большой горизонтальный отступ.

2018-10-29 13:59 UTC, AShepelevv commented on task1.tex
>  	\hspace{28pt}{\Large\textbf{Геометрия \hfill Планиметрия}}
В 26 строчке тоже.

2018-10-29 13:59 UTC, AShepelevv commented on task1.tex
>  	\hspace{28pt}{\Large\textbf{Геометрия \hfill Планиметрия}}
Речь идет об отступах уже в pdf файле.

2018-10-29 15:30 UTC, enscogitans commented
> @enscogitans Но ведь ничего не изменилось, перед "Заголовка" попрежнему 28pt + абзацный отступ. А второго слагаемого быть не должно.

Ну так в задании и указано 28pt. Что не так?

2018-10-30 14:59 UTC, AShepelevv requested changes

2018-10-30 14:59 UTC, AShepelevv commented on task1.tex
>  	Для плоского треугольника со сторонами $a, b, c$ и углом $\alpha$, лежащим против стороны $a$, справедливо соотношение
Здесь `$a, b, c$` пробелы будут игнорироваться, а, значит, не будет пробелов после знаков препинания, что крайне неправильно. Чтобы это исправить, нужно каждую переменную в отдельной формуле писать.

2018-10-30 15:14 UTC, merged